- name : Testing play
  hosts: myhosts
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print host information
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is reachable with IP {{ ansible_host }}"
      when: ansible_host is defined

    - name: Setup docker apt repository
      # run raw commands
      ansible.builtin.shell: |
        #!/bin/bash
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install docker
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker.io
          - docker-compose-plugin
        state: latest

    - name: Copy docker-compose
      copy:
        src: ./Docker/
        dest: /opt/Docker/

    - name: Run docker-compose
      community.docker.docker_compose_v2:
        project_src: /opt/Docker
        state: present 

    