- name : Testing play
  hosts: myhosts
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print host information
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is reachable with IP {{ ansible_host }}"
      when: ansible_host is defined

    - name: Install docker
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker.ce
          # - docker-compose-plugin
        state: latest

    - name: Run docker-compose
      community.docker.docker_compose_v2:
        project_src: ./Docker
        state: present 

    